name: EUHealth Weekly Refresh

on:
  schedule:
    - cron: "0 6 * * 1"   # Mondays 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: euhealth-cache-refresh
  cancel-in-progress: false

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e . requests python-dotenv huggingface_hub faiss-cpu

      - name: Build EUHealth datastore (live pull + embed + index)
        env:
          EMBED_PROVIDER: ${{ secrets.EMBED_PROVIDER }}
          EMBED_MODEL: ${{ secrets.EMBED_MODEL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          EUFDP_BASE: https://fair.healthinformationportal.eu
        run: |
          echo "Building EUHealth datastore with provider=$EMBED_PROVIDER model=$EMBED_MODEL"
          python - <<'PY'
          from tooluniverse.euhealth.euhealth_live import build_euhealth_collection
          build_euhealth_collection(collection="euhealth")
          PY

      - name: Upload datastore to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          tu-datastore sync-hf upload \
            --collection euhealth \
            --repo agenticx/tooluniverse-datastores

