#!/bin/bash
# 快速演示多语言构建功能

echo "🌍 ToolUniverse 多语言文档构建演示"
echo "======================================"
echo ""
echo "✨ 已完成的配置："
echo ""
echo "1. ✅ quick_doc_build.sh - 默认构建中英文"
echo "   DOC_LANGUAGES 默认值: en,zh_CN"
echo ""
echo "2. ✅ quick_doc_build_cn.sh - 默认构建中英文"
echo "   DOC_LANGUAGES 默认值: zh_CN,en"
echo ""
echo "3. ✅ 自动创建语言选择页"
echo "   位置: _build/html/index.html"
echo ""
echo "4. ✅ 自动更新翻译文件"
echo "   位置: locale/zh_CN/LC_MESSAGES/"
echo ""
echo "5. ✅ 多语言目录结构"
echo "   英文: _build/html/en/"
echo "   中文: _build/html/zh-CN/"
echo ""
echo "📝 使用方法："
echo ""
echo "# 默认构建（中英文）"
echo "./quick_doc_build.sh"
echo ""
echo "# 仅构建英文"
echo "DOC_LANGUAGES=en ./quick_doc_build.sh"
echo ""
echo "# 仅构建中文"  
echo "DOC_LANGUAGES=zh_CN ./quick_doc_build.sh"
echo ""
echo "🎨 主题特性："
echo "   ✅ Shibuya 现代主题"
echo "   ✅ 完整的左侧导航栏"
echo "   ✅ 深色/浅色模式"
echo "   ✅ 移动端响应式"
echo "   ✅ 多语言支持"
echo ""
echo "📚 相关文档："
echo "   - QUICK_BUILD_GUIDE.md - 快速构建指南"
echo "   - I18N_GUIDE.md - 翻译指南"
echo "   - MULTILANG_README.md - 多语言系统说明"
echo ""
echo "🚀 现在就试试："
echo "   ./quick_doc_build.sh"
echo ""
